<?php

$accurateClientId = env('ACCURATE_CLIENT_ID');

$fbPageToken = env('FB_PAGE_TOKEN');

$fbApiUrl = 'https://graph.facebook.com/v9.0/';

return [
    /*
     * URL to login to Accurate.
     */
    'accurate_login_url' => 'https://accurate.id/oauth/authorize?'.http_build_query([
        'client_id' => $accurateClientId,
        'response_type' => 'code',
        'redirect_uri' => 'https://accurate-bot.herokuapp.com/accurate-callback',
        'scope' => 'item_view item_save sales_invoice_view',
    ]),

    /*
     * FB base API URL.
     */
    'fb_api_url' => $fbApiUrl,

    /*
     * Token to allow this app to send message using Messenger Send API.
     */
    'fb_page_token' => $fbPageToken,

    /*
     * Send API endpoint URL.
     */
    'fb_sendapi_url' => sprintf(
        $fbApiUrl.'me/messages?access_token=%s',
        $fbPageToken,
    ),

    /*
     * Token generated by us to verify that the webhook is valid and usable by Messenger.
     */
    'fb_verify_token' => env('FB_VERIFY_TOKEN'),

    /*
     * A boolean to indicate whether "typing on" should be sent to Messenger.
     */
    'typing_on' => env('TYPING_ON', false),

    /*
     * Weather API key.
     */
    'weather_api_key' => env('WEATHER_API_KEY'),

    /*
     * Weather API endpoint URL.
     */
    'weather_api_url' => 'http://api.openweathermap.org/data/2.5/weather',

    /*
     * Translate API endpoint URL.
     */
    'translate_api_url' => 'https://amm-api-translate.herokuapp.com/translate?',

    /*
     * Wikipedia API endpoint URL.
     */
    'wikipedia_api_url' => 'https://id.wikipedia.org/w/api.php',

    /*
     * SERP API endpoint URL.
     */
    'serp_api_url' => 'https://api.scaleserp.com/search',
];
