<?php

$fbPageToken = env('FB_PAGE_TOKEN');

return [
    /*
     * Token to allow this app to send message using Messenger Send API.
     */
    'fb_page_token' => $fbPageToken,

    /*
     * Send API endpoint URL.
     */
    'fb_sendapi_url' => sprintf(
        'https://graph.facebook.com/v9.0/me/messages?access_token=%s',
        $fbPageToken,
    ),
    
    'fb_user_url' => env('FB_USER_URL'),

    /*
     * Token generated by us to verify that the webhook is valid and usable by Messenger.
     */
    'fb_verify_token' => env('FB_VERIFY_TOKEN'),
    

    /*
     * Weather API key.
     */
    'weather_api_key' => env('WEATHER_API_KEY'),

    /*
     * Weather API endpoint URL.
     */
    'weather_api_url' => 'http://api.openweathermap.org/data/2.5/weather',
];
